# Generated by Django 5.0.4 on 2025-04-13 15:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='profile_pics/default.png', upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('farmer_type', models.CharField(choices=[('small', 'Small Scale Farmer'), ('medium', 'Medium Scale Farmer'), ('large', 'Large Scale Farmer'), ('hobbyist', 'Hobbyist/Gardener'), ('commercial', 'Commercial Farmer'), ('other', 'Other')], default='small', max_length=20)),
                ('farming_experience', models.CharField(choices=[('beginner', 'Beginner (0-2 years)'), ('intermediate', 'Intermediate (3-5 years)'), ('experienced', 'Experienced (6-10 years)'), ('expert', 'Expert (10+ years)')], default='beginner', max_length=20)),
                ('preferred_crops', models.CharField(blank=True, max_length=255)),
                ('farm_size', models.FloatField(blank=True, help_text='Farm size in acres', null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
