# Generated by Django 5.0.4 on 2025-04-20 06:03

import community.models
import community.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=community.storage.MobileCompatibleStorage(), upload_to='community_posts/%Y/%m/', validators=[community.models.validate_file_size, community.models.validate_file_extension]),
        ),
    ]
